#!/bin/sh
# Set-up a quilt environment and run a command or a shell

# Create patches directory if it does not exist yet
if ! mkdir -p "$(dirname $0)/patches" ; then
    echo >&2 "Unable to create patches directory"
    exit 1
fi

export QUILTRC="$(cd $(dirname $0) && pwd)/quiltrc"

if [ $# -gt 1 ]
then
    exec "$@"
else
    exec ${SHELL:-sh}
fi
