#!/bin/sh
# Configure a quilt environment
# Use with "export QUILTRC=$(pwd)/quiltrc"
#
# Quick documentation from https://wiki.debian.org/UsingQuilt:
# * "quilt push -a" applies all patches
# * "quilt new my_patch.patch" creates a new patch
# * "quilt add a_file.c" adds a file to the current patch
# * "quilt refresh" writes modifications in the current patch
# * "quilt push my_patch.patch" edit a specific patch
# * "quilt pop -a" un-applies all patches
# * "quilt diff", "quilt series", "quilt applied": status-related commands

# Create patches relative to src-linux-*, not the main directory
QUILT_PATCHES="../patches"

# Options passed to GNU diff when generating patches
QUILT_DIFF_OPTS="--show-c-function"

# Options passed to GNU patch when applying patches
QUILT_PATCH_OPTS="--unified"

# Options to pass to commands
QUILT_PUSH_ARGS="--color=auto"
QUILT_DIFF_ARGS="-p ab --no-index --no-timestamps --color=auto"
QUILT_REFRESH_ARGS="-p ab --no-index --no-timestamps"
QUILT_SERIES_ARGS="--color=auto"
QUILT_PATCHES_ARGS="--color=auto"

# Always pass --no-index --no-timestamps to commands
QUILT_NO_DIFF_INDEX=1
QUILT_NO_DIFF_TIMESTAMPS=1

# Configure colors
QUILT_COLORS="diff_hdr=1;32:diff_add=1;34:diff_rem=1;31:diff_hunk=1;33:diff_ctx=35:diff_cctx=33"
