FROM fedora:40
LABEL Description="Fedora 40 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# dnf was replaced with dnf5: https://fedoraproject.org/wiki/Changes/MajorUpgradeOfMicrodnf
RUN \
    dnf install -q -y --setopt=deltarpm=false dnf5 && \
    dnf5 update -q -y --setopt=deltarpm=false && \
    dnf5 install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        diffutils \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.i686 \
        libmnl-devel.x86_64 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python-unversioned-command \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-z3 \
        python2-devel \
        SDL2-devel \
        which \
        wine \
        xorg-x11-server-Xvfb && \
    dnf5 clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["xvfb-run", "/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/processor:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/processor:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
#       clang: clang version 17.0.2 (Fedora 17.0.2-1.fc40)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 13.2.1 20230728 (Fedora MinGW 13.2.1-5.fc39)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 13.2.1 20230728 (Fedora MinGW 13.2.1-5.fc39)
#       wine: wine-8.18 (Staging)
#       Linux kernel: 6.6.0-0.rc6.47.fc40.x86_64
#       /lib/ld-linux.so.2: ld.so (GNU libc) development release version 2.38.9000.
#       python: Python 3.12.0
#       python3: Python 3.12.0
#       javac: javac 11.0.20
#       java: openjdk 11.0.20 2023-07-18
#       rustc: rustc 1.73.0 (cc66ad468 2023-10-03) (Fedora 1.73.0-1.fc40)
#       cargo: cargo 1.73.0
#       coqc: The Coq Proof Assistant, version 8.17.1 compiled with OCaml 5.1.0
#       openssl: OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
