FROM fedora:22
LABEL Description="Fedora 22 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8 \
    PKGCONF=pkg-config

# Fedora<28 does not provide python3-z3 nor python-z3
# Fedora<24 does not provide cargo
RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        clang \
        coq \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-1.8.0-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.x86_64 \
        libmnl-devel.i686 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        pkgconfig \
        pulseaudio-libs-devel \
        python3 \
        python3-cffi \
        python3-crypto \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python-argparse \
        python-cffi \
        python-crypto \
        python-devel \
        python-gmpy2 \
        python-pillow \
        SDL2-devel \
        which \
        wine && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust%
#    In sub-directories:
#       c:
#       glossaries: check_sort_order.py
#       java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#       linux:
#       python: clang_cfi_typeid.py z3_example.py
#       python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py eth_functions_keccak.py parse_openssl_enc.py rsa_tests.py
#       python/network:
#       python/network/dnssec: verify_dnssec.py
#       python/qrcode:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries: check_sort_order.py
#          java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#          linux: pulseaudio_echo sdl_v4l_video
#          python: clang_cfi_typeid.py z3_example.py
#          python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py eth_functions_keccak.py parse_openssl_enc.py rsa_tests.py
#          python/network:
#          python/network/dnssec: verify_dnssec.py
#          python/qrcode:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
#       clang: clang version 3.5.0 (tags/RELEASE_350/final)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 5.1.0 20150422 (Fedora MinGW 5.1.0-2.fc22)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 5.1.0 20150422 (Fedora MinGW 5.1.0-2.fc22)
#       wine: wine-1.9.12 (Staging)
#       Linux kernel: 4.4.14-200.fc22.x86_64
#       python3: Python 3.4.2
#       coqc: The Coq Proof Assistant, version 8.4pl6 (April 2015) compiled on Apr 12 2015 02:22:31 with OCaml 4.02.0
#       openssl: OpenSSL 1.0.1k-fips 8 Jan 2015
