FROM ubuntu:12.04
LABEL Description="Ubuntu 12.04 LTS Precise Pangolin with build dependencies for shared"

# Do not install coq because it is too old (8.3pl4) for some features
# Do not install libmnl-dev because mnl_attr_for_each() performs arithmetics on void*
# Do not install python-crypto nor python3-crypto because they are too old
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        clang \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libpulse-dev \
        linux-headers-generic \
        make \
        pkg-config \
        python3 \
        python-argparse \
        binutils-mingw-w64 \
        gcc-mingw-w64 \
        wine && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]
