FROM fedora:28
LABEL Description="Fedora 28 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.x86_64 \
        libmnl-devel.i686 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-z3 \
        python2-cffi \
        python2-devel \
        python2-gmpy2 \
        python2-pillow \
        python2-pycryptodomex \
        python2-z3 \
        SDL2-devel \
        which \
        wine && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: boot/efi% latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
#       clang: clang version 6.0.1 (tags/RELEASE_601/final)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 7.3.0 20180125 (Fedora MinGW 7.3.0-1.fc28)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 7.3.0 20180125 (Fedora MinGW 7.3.0-1.fc28)
#       wine: wine-4.0 (Staging)
#       Linux kernel: 5.0.16-100.fc28.x86_64
#       python3: Python 3.6.8
#       javac: javac 11.0.3
#       rustc: rustc 1.33.0
#       cargo: cargo 1.33.0
#       coqc: The Coq Proof Assistant, version 8.7.1 (February 2018) compiled on Feb 25 2018 0:28:30 with OCaml 4.06.0
#       openssl: OpenSSL 1.1.0i-fips  14 Aug 2018
