FROM ubuntu-debootstrap:14.04
LABEL Description="Ubuntu 14.04 LTS Trusty Tahr with build dependencies for shared"

# libnetlink (previously provided by iproute-dev) disappeared.
# musl malloc does not seem to support fallback to mmap and brk fails in "make test"
#   so do not install musl-dev and musl-tools packages
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libpulse-dev \
        libsdl2-dev \
        linux-headers-generic \
        make \
        pkg-config \
        python3 \
        python3-cffi \
        python3-dev \
        python3-numpy \
        python-argparse \
        python-cffi \
        python-dev \
        python-numpy \
        wine && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]
