FROM fedora:26
LABEL Description="Fedora 26 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Fedora 26 merged python-argparse into python2-libs
# Building kernel modules now requires elfutils-libelf-devel
# Fedora<28 does not provide python3-z3 nor python-z3
# Fedora 26 provides a version of Rust (1.26.0) which is too old
RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        clang \
        coq \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-9-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.x86_64 \
        libmnl-devel.i686 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python2-cffi \
        python2-devel \
        python2-gmpy2 \
        python2-pillow \
        python2-pycryptodomex \
        redhat-rpm-config \
        SDL2-devel \
        which \
        wine && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python: z3_example.py
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       verification:
#    With gcc -m32:
#       Global blacklist: boot/efi% latex% rust%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python: z3_example.py
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)
#       clang: clang version 4.0.1 (tags/RELEASE_401/final)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 7.2.0 20170814 (Fedora MinGW 7.2.0-1.fc26)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 7.2.0 20170814 (Fedora MinGW 7.2.0-1.fc26)
#       wine: wine-3.6 (Staging)
#       Linux kernel: 4.16.11-100.fc26.x86_64
#       python3: Python 3.6.5
#       javac: javac 9.0.4
#       java: openjdk 9.0.4
#       coqc: The Coq Proof Assistant, version 8.6 (February 2017) compiled on Feb 10 2017 14:7:49 with OCaml 4.04.0
#       openssl: OpenSSL 1.1.0h-fips  27 Mar 2018
