FROM fedora:41
LABEL Description="Fedora 41 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

RUN \
    dnf install -q -y --setopt=deltarpm=false dnf5 && \
    dnf5 update -q -y --setopt=deltarpm=false && \
    dnf5 install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        diffutils \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.i686 \
        libmnl-devel.x86_64 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python-unversioned-command \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-setuptools \
        python3-z3 \
        python2-devel \
        SDL2-devel \
        which \
        wine \
        xorg-x11-server-Xvfb && \
    dnf5 clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["xvfb-run", "/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/processor:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/processor:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 14.1.1 20240507 (Red Hat 14.1.1-1)
#       clang: clang version 18.1.3 (Fedora 18.1.3-2.fc41)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 14.1.1 20240507 (Fedora MinGW 14.1.1-1.fc41)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 14.1.1 20240507 (Fedora MinGW 14.1.1-1.fc41)
#       wine: wine-9.5 (Staging)
#       Linux kernel: 6.9.0-0.rc7.20240510git448b3fe5a0ea.62.fc41.x86_64
#       /lib/ld-linux.so.2: ld.so (GNU libc) development release version 2.39.9000.
#       python: Python 3.12.3
#       python3: Python 3.12.3
#       javac: javac 11.0.23
#       java: openjdk 11.0.23 2024-04-16
#       rustc: rustc 1.78.0 (9b00956e5 2024-04-29) (Fedora 1.78.0-1.fc41)
#       cargo: cargo 1.78.0
#       coqc: The Coq Proof Assistant, version 8.18.0 compiled with OCaml 5.1.1
#       openssl: OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
