FROM debian:bullseye-slim
LABEL Description="Debian 11 Bullseye with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Installing openjdk-11-jre-headless requires /usr/share/man/man1 to exist
# Install apt-utils first, in order to apply package configuration tasks
# Install wine last, because otherwise apt fails to configure it
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    mkdir -p /usr/share/man/man1 && \
    apt-get install --no-install-recommends --no-install-suggests -qqy apt-utils && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        cargo \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libpulse-dev \
        libsdl2-dev \
        libssl-dev \
        linux-headers-amd64 \
        m4 \
        make \
        musl-dev \
        musl-tools \
        openjdk-11-jdk \
        openssh-client \
        openssl \
        pkgconf \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-dev \
        python3-gmpy2 \
        python3-nacl \
        python3-numpy \
        python3-pil \
        python3-pycryptodome \
        python3-z3 \
        sagemath && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        wine \
        wine32 \
        wine64 && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust/download_web%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust/download_web%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: ok
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (Debian 10.2.1-6) 10.2.1 20210110
#       clang: Debian clang version 11.0.1-2
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 10-win32 20210110
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 10-win32 20210110
#       wine: wine-5.0.3 (Debian 5.0.3-3)
#       Linux kernel: 5.10.0-15-amd64
#       /lib/ld-musl-x86_64.so.1: musl libc (x86_64) Version 1.2.2
#       python3: Python 3.9.2
#       javac: javac 11.0.15
#       java: openjdk 11.0.15 2022-04-19
#       rustc: rustc 1.48.0
#       cargo: cargo 1.46.0
#       coqc: The Coq Proof Assistant, version 8.12.0 (November 2020) compiled on Nov 25 2020 6:34:32 with OCaml 4.11.1
#       openssl: OpenSSL 1.1.1n  15 Mar 2022
