FROM debian:buster-slim
LABEL Description="Debian 10 Buster with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Installing openjdk-11-jre-headless requires /usr/share/man/man1 to exist
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    mkdir -p /usr/share/man/man1 && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        cargo \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libpulse-dev \
        libsdl2-dev \
        libssl-dev \
        linux-headers-amd64 \
        m4 \
        make \
        musl-dev \
        musl-tools \
        openjdk-11-jdk \
        openssh-client \
        openssl \
        pkgconf \
        python3 \
        python3-cffi \
        python3-crypto \
        python3-cryptography \
        python3-dev \
        python3-gmpy2 \
        python3-nacl \
        python3-numpy \
        python3-pil \
        python3-pycryptodome \
        python-cffi \
        python-crypto \
        python-dev \
        python-gmpy2 \
        python-numpy \
        python-pil \
        python-z3 \
        sagemath \
        wine \
        wine32 \
        wine64 && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python: z3_example.py
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python: z3_example.py
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: ok
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (Debian 8.3.0-6) 8.3.0
#       clang: clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 8.3-win32 20190406
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 8.3-win32 20190406
#       wine: wine-4.0 (Debian 4.0-2)
#       Linux kernel: 4.19.0-20-amd64
#       /lib/ld-musl-x86_64.so.1: musl libc (x86_64) Version 1.1.21
#       python3: Python 3.7.3
#       javac: javac 11.0.15
#       java: openjdk 11.0.15 2022-04-19
#       rustc: rustc 1.41.1
#       cargo: cargo 1.42.1
#       coqc: The Coq Proof Assistant, version 8.9.0 (February 2019) compiled on Feb 6 2019 17:43:20 with OCaml 4.05.0
#       openssl: OpenSSL 1.1.1n  15 Mar 2022
