FROM fedora:33
LABEL Description="Fedora 33 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        diffutils \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.i686 \
        libmnl-devel.x86_64 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python-unversioned-command \
        python3 \
        python3-cffi \
        python3-crypto \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-z3 \
        python2-devel \
        python2-pillow \
        SDL2-devel \
        which \
        wine \
        xorg-x11-server-Xvfb && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["xvfb-run", "/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 10.2.1 20200826 (Red Hat 10.2.1-3)
#       clang: clang version 11.0.0 (Fedora 11.0.0-0.2.rc1.fc33)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 10.2.1 20200723 (Fedora MinGW 10.2.1-2.fc33)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 10.2.1 20200723 (Fedora MinGW 10.2.1-2.fc33)
#       wine: wine-5.16 (Staging)
#       Linux kernel: 5.8.8-300.fc33.x86_64
#       python: Python 3.9.0rc1
#       python3: Python 3.9.0rc1
#       javac: javac 11.0.9-ea
#       java: openjdk 11.0.9-ea 2020-10-20
#       rustc: rustc 1.46.0
#       cargo: cargo 1.46.0
#       coqc: The Coq Proof Assistant, version 8.12.0 (September 2020) compiled on Sep 2 2020 0:00:00 with OCaml 4.11.1
