FROM fedora:29
LABEL Description="Fedora 29 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.x86_64 \
        libmnl-devel.i686 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-z3 \
        python2-cffi \
        python2-devel \
        python2-gmpy2 \
        python2-pillow \
        python2-pycryptodomex \
        python2-z3 \
        SDL2-devel \
        which \
        wine && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust/asymkeyfind% rust/check_linux_pass% rust/download_web%
#       In sub-directories:
#          c: gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
#       clang: clang version 7.0.1 (Fedora 7.0.1-6.fc29)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 8.3.0 20190222 (Fedora MinGW 8.3.0-2.fc29)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 8.3.0 20190222 (Fedora MinGW 8.3.0-2.fc29)
#       wine: wine-4.15 (Staging)
#       Linux kernel: 5.3.11-100.fc29.x86_64
#       python3: Python 3.7.5
#       javac: javac 11.0.5
#       java: openjdk 11.0.5 2019-10-15
#       rustc: rustc 1.39.0
#       cargo: cargo 1.39.0
#       coqc: The Coq Proof Assistant, version 8.7.1 (July 2018) compiled on Jul 12 2018 23:40:45 with OCaml 4.07.0
#       openssl: OpenSSL 1.1.1d FIPS  10 Sep 2019
