FROM ubuntu:22.04
LABEL Description="Ubuntu 22.04 LTS Jammy Jellyfish with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Install apt-utils first, in order to apply package configuration tasks
# Debian 12 (and Ubuntu 22.04) removed sagemath because it failed to build from source
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy apt-utils && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        cargo \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libpulse-dev \
        libsdl2-dev \
        libssl-dev \
        linux-headers-generic \
        m4 \
        make \
        musl-dev \
        musl-tools \
        openjdk-11-jdk \
        openssh-client \
        openssl \
        pkgconf \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-dev \
        python3-gmpy2 \
        python3-nacl \
        python3-numpy \
        python3-pil \
        python3-pycryptodome \
        python3-z3 && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        wine-stable \
        wine32 \
        wine64 && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: ok
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
#       clang: Ubuntu clang version 14.0.0-1ubuntu1
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 10-win32 20220113
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 10-win32 20220113
#       wine: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
#       Linux kernel: 5.15.0-39-generic
#       /lib/ld-linux.so.2: ld.so (Ubuntu GLIBC 2.35-0ubuntu3) stable release version 2.35.
#       /lib/ld-musl-x86_64.so.1: musl libc (x86_64) Version 1.2.2
#       python3: Python 3.10.4
#       javac: javac 11.0.15
#       java: openjdk 11.0.15 2022-04-19
#       rustc: rustc 1.59.0
#       cargo: cargo 1.59.0
#       coqc: The Coq Proof Assistant, version 8.15.0 compiled with OCaml 4.13.1
#       openssl: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
