FROM debian:forky-slim
LABEL Description="Debian 14 Forky with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Install apt-utils first, in order to apply package configuration tasks
# Install wine last, because otherwise apt fails to configure it
# Remove sagemath, as it is no longer packaged
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy apt-utils && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        cargo \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libomp-dev \
        libpulse-dev \
        libsdl2-dev \
        libssl-dev \
        linux-headers-amd64 \
        m4 \
        make \
        musl-dev \
        musl-tools \
        openjdk-26-jdk-headless \
        openssh-client \
        openssl \
        pkgconf \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-dev \
        python3-gmpy2 \
        python3-nacl \
        python3-numpy \
        python3-pil \
        python3-pycryptodome \
        python3-setuptools \
        python3-z3 && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        wine \
        wine32 \
        wine64 && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/processor:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/processor:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: ok
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (Debian 15.2.0-4) 15.2.0
#       clang: Debian clang version 19.1.7 (3+b2)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 14-win32
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 14-win32
#       wine: wine-10.0 (Debian 10.0~repack-6)
#       Linux kernel: 6.16.9+deb14-amd64
#       /lib/ld-linux.so.2: ld.so (Debian GLIBC 2.41-12) stable release version 2.41.
#       /lib/ld-musl-x86_64.so.1: musl libc (x86_64) Version 1.2.5
#       python3: Python 3.13.7
#       javac: javac 26-ea
#       java: openjdk 26-ea 2026-03-17
#       rustc: rustc 1.87.0 (17067e9ac 2025-05-09) (built from a source tarball)
#       cargo: cargo 1.87.0 (99624be96 2025-05-06) (built from a source tarball)
#       coqc: The Coq Proof Assistant, version 8.20.1 compiled with OCaml 5.3.0
#       openssl: OpenSSL 3.5.4 30 Sep 2025 (Library: OpenSSL 3.5.4 30 Sep 2025)
