FROM base/archlinux
# Use https://github.com/docker/docker/blob/master/contrib/mkimage-arch.sh
# to build a local Arch Linux image, from an Arch Linux distribution.
# (Download https://raw.githubusercontent.com/docker/docker/master/contrib/mkimage-arch.sh
# and https://raw.githubusercontent.com/docker/docker/master/contrib/mkimage-arch-pacman.conf)
LABEL Description="Arch Linux with build dependencies for shared"

RUN \
    echo '[multilib]' >> /etc/pacman.conf && \
    echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf && \
    pacman --noconfirm -Sy && \
    pacman --noconfirm -S \
        base-devel \
        clang \
        coq \
        gcc \
        gdb \
        gtk3 \
        kernel-headers-musl \
        libpulse \
        linux-headers \
        make \
        mingw-w64-gcc \
        musl \
        pkg-config \
        python \
        python-cffi \
        python-numpy \
        python2 \
        python2-cffi \
        python2-numpy \
        sdl2 \
        which \
        wine && \
    pacman --noconfirm -Sc && rm -rf /var/cache/pacman/pkg/*

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]
