FROM alpine:3.5
LABEL Description="Alpine Linux 3.5 with build dependencies for shared"

# Alpine does not provide coq, mingw-w64, py3-z3
# Alpine<3.8 does not provide pulseaudio-dev
# Alpine<3.6 does not provide cargo
RUN \
    apk --no-cache --update add \
        clang \
        clang-dev \
        gcc \
        gdb \
        gmp-dev \
        gtk+3.0-dev \
        iproute2 \
        libmnl-dev \
        libressl \
        linux-grsec-dev \
        linux-headers \
        llvm-dev \
        make \
        musl-dev \
        musl-utils \
        openjdk8 \
        openssh \
        py-numpy \
        py2-cffi \
        py2-crypto \
        py2-pillow \
        py3-cffi \
        py3-crypto \
        py3-pillow \
        python2-dev \
        python3-dev \
        sdl2-dev && \
    rm -rf /var/cache/apk/*

# Add OpenJDK to $PATH
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust% windows%
#    In sub-directories:
#       c: x86-read_64b_regs_in_32b_mode
#       glossaries: check_sort_order.py
#       java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#       linux: pulseaudio_echo
#       python: cffi_numpy.py clang_cfi_typeid.py z3_example.py
#       python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py eth_functions_keccak.py parse_openssl_enc.py rsa_tests.py
#       python/network:
#       python/network/dnssec: verify_dnssec.py
#       python/qrcode:
#       verification: ackermann.vo
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: not working
#       clang -m64: ok
#       clang -m32: not working
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: not working
#       i686-w64-mingw32-gcc: not working
#    Versions:
#       gcc: gcc (Alpine 6.2.1) 6.2.1 20160822
#       clang: clang version 3.8.1 (tags/RELEASE_381/final)
#       Linux kernel: 4.4.59-0-grsec
#       /lib/ld-musl-x86_64.so.1: musl libc (x86_64) Version 1.1.15
#       python3: Python 3.5.6
#       openssl: LibreSSL 2.4.4
