FROM debian:wheezy-slim
LABEL Description="Debian 7 Wheezy with build dependencies for shared"

# Do not install coq because it is too old (8.3pl4) for some features
# Do not install wine because it is too ols (1.4.1) to work in containers
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        clang \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libpulse-dev \
        linux-headers-amd64 \
        make \
        openssl \
        pkg-config \
        python3 \
        python3-crypto \
        python3-numpy \
        python-argparse \
        python-crypto \
        python-numpy && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]
