FROM ubuntu:12.04
LABEL Description="Ubuntu 12.04 LTS Precise Pangolin with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8 \
    PKGCONF=pkg-config

# Do not install coq because it is too old (8.3pl4) for some features
# Do not install libmnl-dev because mnl_attr_for_each() performs arithmetic on void*
# Do not install python-crypto nor python3-crypto because they are too old
# Ubuntu<16.04 does not provide python-z3
# Ubuntu<14.04 does not provide cargo, python-pil nor python3-pil
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        clang \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libpulse-dev \
        linux-headers-generic \
        make \
        openjdk-7-jdk \
        pkg-config \
        python3 \
        python-argparse \
        wine && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust%
#    In sub-directories:
#       c:
#       glossaries: check_sort_order.py
#       java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#       linux: enum_link_addrs sdl_v4l_video
#       python: cffi_example.py cffi_numpy.py clang_cfi_typeid.py z3_example.py
#       python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py parse_openssl_enc.py rsa_tests.py tpm_decode_bios_measurements.py tpm_ea_policy.py
#       python/network: udp_multihome.py
#       python/network/dnssec: verify_dnssec.py
#       python/qrcode: hello_qr_decode.py
#       verification: ackermann.vo
#    With gcc -m32:
#       Global blacklist: latex% rust%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries: check_sort_order.py
#          java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python: cffi_example.py cffi_numpy.py clang_cfi_typeid.py z3_example.py
#          python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py parse_openssl_enc.py rsa_tests.py tpm_decode_bios_measurements.py tpm_ea_policy.py
#          python/network: udp_multihome.py
#          python/network/dnssec: verify_dnssec.py
#          python/qrcode: hello_qr_decode.py
#          verification: ackermann.vo
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: only compiling
#       i686-w64-mingw32-gcc: only compiling
#    Versions:
#       gcc: gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
#       clang: Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 4.6.3
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 4.6.3
#       wine: wine-1.4
#       Linux kernel: 3.2.0-126-generic
