FROM alpine:3.12
LABEL Description="Alpine Linux 3.12 with build dependencies for shared"

# Alpine does not provide coq
RUN \
    apk --no-cache --update add \
        cargo \
        clang \
        clang-dev \
        gcc \
        gdb \
        gmp-dev \
        gtk+3.0-dev \
        iproute2 \
        libmnl-dev \
        libressl \
        linux-lts-dev \
        linux-headers \
        llvm-dev \
        make \
        mingw-w64-gcc \
        musl-dev \
        musl-utils \
        nss \
        openjdk11 \
        openssh \
        openssl \
        openssl-dev \
        pulseaudio-dev \
        py3-cffi \
        py3-crypto \
        py3-numpy \
        py3-pillow \
        py3-setuptools \
        py3-z3 \
        python2-dev \
        python3-dev \
        sdl2-dev \
        z3-dev && \
    rm -rf /var/cache/apk/*

# Add OpenJDK to $PATH
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c: x86-read_64b_regs_in_32b_mode
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification: ackermann.vo
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: not working
#       clang -m64: ok
#       clang -m32: not working
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: only compiling
#       i686-w64-mingw32-gcc: not working
#    Versions:
#       gcc: gcc (Alpine 9.3.0) 9.3.0
#       clang: Alpine clang version 10.0.0 (https://gitlab.alpinelinux.org/alpine/aports.git 7445adce501f8473efdb93b17b5eaf2f1445ed4c)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 9.3.0
#       Linux kernel: 5.4.43-1-lts
#       python3: Python 3.8.3
#       javac: javac 11.0.7
#       java: openjdk 11.0.7 2020-04-14
#       rustc: rustc 1.43.1
#       cargo: cargo 1.43.0
