FROM fedora:32
LABEL Description="Fedora 32 with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# Fedora>=32 dropped Python 2 support
# Wine requires an X11 server in order to work properly: use Xvfb in a container
RUN \
    dnf update -q -y --setopt=deltarpm=false && \
    dnf install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        diffutils \
        elfutils-libelf-devel \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-11-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.i686 \
        libmnl-devel.x86_64 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python-unversioned-command \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-z3 \
        python2-devel \
        python2-pillow \
        python2-pycryptodomex \
        SDL2-devel \
        which \
        wine \
        xorg-x11-server-Xvfb && \
    dnf clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["xvfb-run", "/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust/download_web%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust/download_web%
#       In sub-directories:
#          c: gtk_alpha_window
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: ok
#    Versions:
#       gcc: gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
#       clang: clang version 10.0.1 (Fedora 10.0.1-3.fc32)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 9.2.1 20190827 (Fedora MinGW 9.2.1-6.fc32)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 9.2.1 20190827 (Fedora MinGW 9.2.1-6.fc32)
#       wine: wine-6.3 (Staging)
#       Linux kernel: 5.11.22-100.fc32.x86_64
#       python: Python 3.8.10
#       python3: Python 3.8.10
#       javac: javac 11.0.11
#       java: openjdk 11.0.11 2021-04-20
#       rustc: rustc 1.52.1 (Fedora 1.52.1-1.fc32)
#       cargo: cargo 1.52.0
#       coqc: The Coq Proof Assistant, version 8.11.2 (June 2020) compiled on Jun 15 2020 0:00:00 with OCaml 4.10.0
#       openssl: OpenSSL 1.1.1k  FIPS 25 Mar 2021
