FROM fedora:43
LABEL Description="Fedora 43 with build dependencies for shared"
# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

RUN \
    dnf install -q -y --setopt=deltarpm=false dnf5 && \
    dnf5 update -q -y --setopt=deltarpm=false && \
    dnf5 install -q -y --setopt=deltarpm=false \
        cargo \
        clang \
        coq \
        diffutils \
        elfutils-libelf-devel \
        gawk \
        gcc \
        gdb \
        glibc-devel.x86_64 \
        glibc-devel.i686 \
        gmp-devel.x86_64 \
        gmp-devel.i686 \
        gtk3-devel \
        java-latest-openjdk-devel \
        kernel \
        kernel-devel \
        libmnl-devel.i686 \
        libmnl-devel.x86_64 \
        m4 \
        make \
        mingw32-gcc \
        mingw64-gcc \
        numpy \
        openssh \
        openssl \
        openssl-devel \
        openssl-devel-engine \
        perl-Getopt-Long \
        perl-Term-ANSIColor \
        pkgconf \
        pulseaudio-libs-devel \
        python-unversioned-command \
        python3 \
        python3-cffi \
        python3-cryptography \
        python3-devel \
        python3-gmpy2 \
        python3-numpy \
        python3-pillow \
        python3-pycryptodomex \
        python3-pynacl \
        python3-setuptools \
        python3-z3 \
        SDL2-devel \
        which \
        wine \
        xorg-x11-server-Xvfb && \
    dnf5 clean all

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["xvfb-run", "/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex%
#    In sub-directories:
#       c:
#       glossaries:
#       java/keystore:
#       linux:
#       python:
#       python/crypto:
#       python/network:
#       python/network/dnssec:
#       python/processor:
#       python/qrcode:
#       rust:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex%
#       In sub-directories:
#          c: gtk_alpha_window openmp_matrix
#          glossaries:
#          java/keystore:
#          linux: pulseaudio_echo sdl_v4l_video
#          python:
#          python/crypto:
#          python/network:
#          python/network/dnssec:
#          python/processor:
#          python/qrcode:
#          rust:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: ok
#       i686-w64-mingw32-gcc: only compiling
#    Versions:
#       gcc: gcc (GCC) 15.0.1 20250313 (Red Hat 15.0.1-0)
#       clang: clang version 20.1.1 (Fedora 20.1.1-1.fc43)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 15.0.1 20250204 (Fedora MinGW 15.0.1-1.fc43)
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 15.0.1 20250204 (Fedora MinGW 15.0.1-1.fc43)
#       wine: wine-10.4 (Staging)
#       Linux kernel: 6.15.0-0.rc0.20250327git1a9239bb4253.5.fc43.x86_64
#       /lib/ld-linux.so.2: ld.so (GNU libc) development release version 2.41.9000.
#       python: Python 3.13.2
#       python3: Python 3.13.2
#       javac: javac 24
#       java: openjdk 24 2025-03-18
#       rustc: rustc 1.85.1 (4eb161250 2025-03-15) (Fedora 1.85.1-1.fc43)
#       cargo: cargo 1.85.1 (d73d2caf9 2024-12-31)
#       coqc: The Coq Proof Assistant, version 8.20.1 compiled with OCaml 5.3.0
#       openssl: OpenSSL 3.5.0-beta1 25 Mar 2025 (Library: OpenSSL 3.5.0-beta1 25 Mar 2025)
