FROM ubuntu:14.04
LABEL Description="Ubuntu 14.04 LTS Trusty Tahr with build dependencies for shared"

# Override the language to force UTF-8 output
ENV LANG=C.UTF-8

# musl malloc does not seem to support fallback to mmap and brk fails in "make test"
#   so do not install musl-dev and musl-tools packages
# Ubuntu<16.04 does not provide python-z3
# Ubuntu 14.04 provides a version of Rust (1.31.0) which is too old
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    dpkg --add-architecture i386 && \
    apt-get -qq update && \
    apt-get install --no-install-recommends --no-install-suggests -qqy \
        binutils-mingw-w64 \
        clang \
        coq \
        gcc-mingw-w64 \
        gcc-multilib \
        gdb \
        libatspi2.0-dev \
        libc-dev \
        libc6-dev-i386 \
        libgmp-dev \
        libgtk-3-dev \
        libmnl-dev \
        libpulse-dev \
        libsdl2-dev \
        linux-headers-generic \
        make \
        openjdk-7-jdk \
        openssh-client \
        openssl \
        pkgconf \
        python3 \
        python3-cffi \
        python3-crypto \
        python3-dev \
        python3-gmpy2 \
        python3-numpy \
        python3-pil \
        python-argparse \
        python-cffi \
        python-crypto \
        python-dev \
        python-gmpy2 \
        python-numpy \
        python-pil \
        wine && \
    apt-get clean

WORKDIR /shared
RUN ln -s shared/machines/run_shared_test.sh /run_shared_test.sh
COPY . /shared/

CMD ["/run_shared_test.sh"]

# make list-nobuild:
#    Global blacklist: latex% rust%
#    In sub-directories:
#       c:
#       glossaries: check_sort_order.py
#       java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#       linux:
#       python: clang_cfi_typeid.py z3_example.py
#       python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py eth_functions_keccak.py parse_openssl_enc.py rsa_tests.py
#       python/network:
#       python/network/dnssec: verify_dnssec.py
#       python/qrcode:
#       verification:
#    With gcc -m32:
#       Global blacklist: latex% rust%
#       In sub-directories:
#          c: gmp_functions gtk_alpha_window
#          glossaries: check_sort_order.py
#          java/keystore: parse_jceks.py parse_pkcs12.py util_asn1.py
#          linux: enum_link_addrs pulseaudio_echo sdl_v4l_video
#          python: clang_cfi_typeid.py z3_example.py
#          python/crypto: bip32_seed_derivation.py chacha20_poly1305_tests.py dhparam_tests.py dsa_tests.py ec_tests.py eth_functions_keccak.py parse_openssl_enc.py rsa_tests.py
#          python/network:
#          python/network/dnssec: verify_dnssec.py
#          python/qrcode:
#          verification:
#    Compilers:
#       gcc -m64: ok
#       gcc -m32: ok
#       clang -m64: ok
#       clang -m32: ok
#       musl-gcc: not working
#       x86_64-w64-mingw32-gcc: only compiling
#       i686-w64-mingw32-gcc: only compiling
#    Versions:
#       gcc: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
#       clang: Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
#       x86_64-w64-mingw32-gcc: x86_64-w64-mingw32-gcc (GCC) 4.8.2
#       i686-w64-mingw32-gcc: i686-w64-mingw32-gcc (GCC) 4.8.2
#       wine: wine-1.6.2
#       Linux kernel: 3.13.0-170-generic
#       python3: Python 3.4.3
#       coqc: The Coq Proof Assistant, version 8.4pl3 (January 2014) compiled on Jan 19 2014 23:14:16 with OCaml 4.01.0
#       openssl: OpenSSL 1.0.1f 6 Jan 2014
