#!/bin/sh
# Create cpuid_enum.h by parsing cpufeature.h from Linux
# (/usr/src/linux/arch/x86/include/asm/cpufeature.h)

if [ $# -ge 1 ]
then
    CPUFEATURE="$1"
else
    CPUFEATURE="cpufeature.h"
fi

if ! [ -r "$CPUFEATURE" ]
then
    echo >&2 "Unable to read $CPUFEATURE"
    exit 1
fi

extract_cpuid_register() {
    cat << EOF

/**
 * $3
 */
__extension__ static const char* const $2[32] = {
EOF
    sed -n 's/^#define X86_FEATURE_\(\S\+\)\s\+('$1'\*32+\s*\([0-9]\+\)\s*).*/    [\2] = "\1",/p' < "$CPUFEATURE" | tr '[A-Z]' '[a-z]'
    echo '};'
}

# Header
cat << EOF
/**
 * This file is automatically generated from $CPUFEATURE.
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * NB: designated initializers are a C99 feature so use __extension__ to be
 *   able to compile with -pendantic.
 */

#ifndef CPUID_ENUM_H
#define CPUID_ENUM_H
EOF

# CPUID data
extract_cpuid_register 0 cpuidstr_1_edx 'cpuid 0x00000001, edx register' | sed 's/"ds"/"dts"/;s/"xmm/"sse/'
extract_cpuid_register 4 cpuidstr_1_ecx 'cpuid 0x00000001, ecx register' | sed 's/"xmm/"sse/'
extract_cpuid_register 9 cpuidstr_7_ebx 'cpuid 0x00000007:0, ebx register'
extract_cpuid_register 1 cpuidstr_ext1_edx 'cpuid 0x80000001, edx register'
extract_cpuid_register 6 cpuidstr_ext1_ecx 'cpuid 0x80000001, ecx register'

# Footer
cat << EOF

#endif
EOF
