/* THIS FILE IS AUTOMATICALLY GENERATED BY Makefile */
/* Include the arch-specific asm/unistd.h file */
#if defined(__arm__)
#include "../asm-arm/unistd.h"
#elif defined(__i386__)
#include "../asm-i386/unistd.h"
#elif defined(__x86_64__)
#include "../asm-x86_64/unistd.h"
#endif
