\usepackage{bbm}
\usepackage{stmaryrd}

% Define math shortcuts
\newcommand{\N}[0]{\ensuremath{\mathbbm{N}}}
\newcommand{\Ns}[0]{\ensuremath{\mathbbm{N^{*}}}}
\newcommand{\Z}[0]{\ensuremath{\mathbbm{Z}}}
\newcommand{\Zs}[0]{\ensuremath{\mathbbm{Z^{*}}}}
\newcommand{\Primes}[0]{\ensuremath{\mathbbm{P}}}
\newcommand{\F}[1]{\ensuremath{\mathbbm{F}_{#1}}}
\newcommand{\ord}[0]{\ensuremath{\text{ord}}}

\newtheorem{theorem}{Theorem}
\newtheorem{definition}{Definition}
